// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms_event.proto

package com.znv.hk8700.protobuf;

public final class PmsEvent {
  private PmsEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class PmsPersonInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use PmsPersonInfo.newBuilder() to construct.
    private PmsPersonInfo() {
      initFields();
    }
    private PmsPersonInfo(boolean noInit) {}
    
    private static final PmsPersonInfo defaultInstance;
    public static PmsPersonInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public PmsPersonInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znv.hk8700.protobuf.PmsEvent.internal_static_com_znv_protobuf_proto_PmsPersonInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znv.hk8700.protobuf.PmsEvent.internal_static_com_znv_protobuf_proto_PmsPersonInfo_fieldAccessorTable;
    }
    
    // required string person_idx = 33;
    public static final int PERSON_IDX_FIELD_NUMBER = 33;
    private boolean hasPersonIdx;
    private java.lang.String personIdx_ = "";
    public boolean hasPersonIdx() { return hasPersonIdx; }
    public java.lang.String getPersonIdx() { return personIdx_; }
    
    // required string person_name = 34;
    public static final int PERSON_NAME_FIELD_NUMBER = 34;
    private boolean hasPersonName;
    private java.lang.String personName_ = "";
    public boolean hasPersonName() { return hasPersonName; }
    public java.lang.String getPersonName() { return personName_; }
    
    // required string dept_name = 35;
    public static final int DEPT_NAME_FIELD_NUMBER = 35;
    private boolean hasDeptName;
    private java.lang.String deptName_ = "";
    public boolean hasDeptName() { return hasDeptName; }
    public java.lang.String getDeptName() { return deptName_; }
    
    // optional int32 id_type = 36;
    public static final int ID_TYPE_FIELD_NUMBER = 36;
    private boolean hasIdType;
    private int idType_ = 0;
    public boolean hasIdType() { return hasIdType; }
    public int getIdType() { return idType_; }
    
    // optional string id_no = 37;
    public static final int ID_NO_FIELD_NUMBER = 37;
    private boolean hasIdNo;
    private java.lang.String idNo_ = "";
    public boolean hasIdNo() { return hasIdNo; }
    public java.lang.String getIdNo() { return idNo_; }
    
    // optional string phone = 38;
    public static final int PHONE_FIELD_NUMBER = 38;
    private boolean hasPhone;
    private java.lang.String phone_ = "";
    public boolean hasPhone() { return hasPhone; }
    public java.lang.String getPhone() { return phone_; }
    
    // optional string pinyin = 39;
    public static final int PINYIN_FIELD_NUMBER = 39;
    private boolean hasPinyin;
    private java.lang.String pinyin_ = "";
    public boolean hasPinyin() { return hasPinyin; }
    public java.lang.String getPinyin() { return pinyin_; }
    
    // optional string addr = 40;
    public static final int ADDR_FIELD_NUMBER = 40;
    private boolean hasAddr;
    private java.lang.String addr_ = "";
    public boolean hasAddr() { return hasAddr; }
    public java.lang.String getAddr() { return addr_; }
    
    // optional string photo_path = 41;
    public static final int PHOTO_PATH_FIELD_NUMBER = 41;
    private boolean hasPhotoPath;
    private java.lang.String photoPath_ = "";
    public boolean hasPhotoPath() { return hasPhotoPath; }
    public java.lang.String getPhotoPath() { return photoPath_; }
    
    // optional int32 sex = 42;
    public static final int SEX_FIELD_NUMBER = 42;
    private boolean hasSex;
    private int sex_ = 0;
    public boolean hasSex() { return hasSex; }
    public int getSex() { return sex_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasPersonIdx) return false;
      if (!hasPersonName) return false;
      if (!hasDeptName) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPersonIdx()) {
        output.writeString(33, getPersonIdx());
      }
      if (hasPersonName()) {
        output.writeString(34, getPersonName());
      }
      if (hasDeptName()) {
        output.writeString(35, getDeptName());
      }
      if (hasIdType()) {
        output.writeInt32(36, getIdType());
      }
      if (hasIdNo()) {
        output.writeString(37, getIdNo());
      }
      if (hasPhone()) {
        output.writeString(38, getPhone());
      }
      if (hasPinyin()) {
        output.writeString(39, getPinyin());
      }
      if (hasAddr()) {
        output.writeString(40, getAddr());
      }
      if (hasPhotoPath()) {
        output.writeString(41, getPhotoPath());
      }
      if (hasSex()) {
        output.writeInt32(42, getSex());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPersonIdx()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(33, getPersonIdx());
      }
      if (hasPersonName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(34, getPersonName());
      }
      if (hasDeptName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(35, getDeptName());
      }
      if (hasIdType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(36, getIdType());
      }
      if (hasIdNo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(37, getIdNo());
      }
      if (hasPhone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(38, getPhone());
      }
      if (hasPinyin()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(39, getPinyin());
      }
      if (hasAddr()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(40, getAddr());
      }
      if (hasPhotoPath()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(41, getPhotoPath());
      }
      if (hasSex()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(42, getSex());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo result;
      
      // Construct using com.znv.protobuf.proto.PmsEvent.PmsPersonInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo();
        return builder;
      }
      
      protected com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.getDescriptor();
      }
      
      public com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo getDefaultInstanceForType() {
        return com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo) {
          return mergeFrom((com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo other) {
        if (other == com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.getDefaultInstance()) return this;
        if (other.hasPersonIdx()) {
          setPersonIdx(other.getPersonIdx());
        }
        if (other.hasPersonName()) {
          setPersonName(other.getPersonName());
        }
        if (other.hasDeptName()) {
          setDeptName(other.getDeptName());
        }
        if (other.hasIdType()) {
          setIdType(other.getIdType());
        }
        if (other.hasIdNo()) {
          setIdNo(other.getIdNo());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasPinyin()) {
          setPinyin(other.getPinyin());
        }
        if (other.hasAddr()) {
          setAddr(other.getAddr());
        }
        if (other.hasPhotoPath()) {
          setPhotoPath(other.getPhotoPath());
        }
        if (other.hasSex()) {
          setSex(other.getSex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 266: {
              setPersonIdx(input.readString());
              break;
            }
            case 274: {
              setPersonName(input.readString());
              break;
            }
            case 282: {
              setDeptName(input.readString());
              break;
            }
            case 288: {
              setIdType(input.readInt32());
              break;
            }
            case 298: {
              setIdNo(input.readString());
              break;
            }
            case 306: {
              setPhone(input.readString());
              break;
            }
            case 314: {
              setPinyin(input.readString());
              break;
            }
            case 322: {
              setAddr(input.readString());
              break;
            }
            case 330: {
              setPhotoPath(input.readString());
              break;
            }
            case 336: {
              setSex(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string person_idx = 33;
      public boolean hasPersonIdx() {
        return result.hasPersonIdx();
      }
      public java.lang.String getPersonIdx() {
        return result.getPersonIdx();
      }
      public Builder setPersonIdx(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPersonIdx = true;
        result.personIdx_ = value;
        return this;
      }
      public Builder clearPersonIdx() {
        result.hasPersonIdx = false;
        result.personIdx_ = getDefaultInstance().getPersonIdx();
        return this;
      }
      
      // required string person_name = 34;
      public boolean hasPersonName() {
        return result.hasPersonName();
      }
      public java.lang.String getPersonName() {
        return result.getPersonName();
      }
      public Builder setPersonName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPersonName = true;
        result.personName_ = value;
        return this;
      }
      public Builder clearPersonName() {
        result.hasPersonName = false;
        result.personName_ = getDefaultInstance().getPersonName();
        return this;
      }
      
      // required string dept_name = 35;
      public boolean hasDeptName() {
        return result.hasDeptName();
      }
      public java.lang.String getDeptName() {
        return result.getDeptName();
      }
      public Builder setDeptName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDeptName = true;
        result.deptName_ = value;
        return this;
      }
      public Builder clearDeptName() {
        result.hasDeptName = false;
        result.deptName_ = getDefaultInstance().getDeptName();
        return this;
      }
      
      // optional int32 id_type = 36;
      public boolean hasIdType() {
        return result.hasIdType();
      }
      public int getIdType() {
        return result.getIdType();
      }
      public Builder setIdType(int value) {
        result.hasIdType = true;
        result.idType_ = value;
        return this;
      }
      public Builder clearIdType() {
        result.hasIdType = false;
        result.idType_ = 0;
        return this;
      }
      
      // optional string id_no = 37;
      public boolean hasIdNo() {
        return result.hasIdNo();
      }
      public java.lang.String getIdNo() {
        return result.getIdNo();
      }
      public Builder setIdNo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIdNo = true;
        result.idNo_ = value;
        return this;
      }
      public Builder clearIdNo() {
        result.hasIdNo = false;
        result.idNo_ = getDefaultInstance().getIdNo();
        return this;
      }
      
      // optional string phone = 38;
      public boolean hasPhone() {
        return result.hasPhone();
      }
      public java.lang.String getPhone() {
        return result.getPhone();
      }
      public Builder setPhone(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhone = true;
        result.phone_ = value;
        return this;
      }
      public Builder clearPhone() {
        result.hasPhone = false;
        result.phone_ = getDefaultInstance().getPhone();
        return this;
      }
      
      // optional string pinyin = 39;
      public boolean hasPinyin() {
        return result.hasPinyin();
      }
      public java.lang.String getPinyin() {
        return result.getPinyin();
      }
      public Builder setPinyin(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPinyin = true;
        result.pinyin_ = value;
        return this;
      }
      public Builder clearPinyin() {
        result.hasPinyin = false;
        result.pinyin_ = getDefaultInstance().getPinyin();
        return this;
      }
      
      // optional string addr = 40;
      public boolean hasAddr() {
        return result.hasAddr();
      }
      public java.lang.String getAddr() {
        return result.getAddr();
      }
      public Builder setAddr(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddr = true;
        result.addr_ = value;
        return this;
      }
      public Builder clearAddr() {
        result.hasAddr = false;
        result.addr_ = getDefaultInstance().getAddr();
        return this;
      }
      
      // optional string photo_path = 41;
      public boolean hasPhotoPath() {
        return result.hasPhotoPath();
      }
      public java.lang.String getPhotoPath() {
        return result.getPhotoPath();
      }
      public Builder setPhotoPath(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhotoPath = true;
        result.photoPath_ = value;
        return this;
      }
      public Builder clearPhotoPath() {
        result.hasPhotoPath = false;
        result.photoPath_ = getDefaultInstance().getPhotoPath();
        return this;
      }
      
      // optional int32 sex = 42;
      public boolean hasSex() {
        return result.hasSex();
      }
      public int getSex() {
        return result.getSex();
      }
      public Builder setSex(int value) {
        result.hasSex = true;
        result.sex_ = value;
        return this;
      }
      public Builder clearSex() {
        result.hasSex = false;
        result.sex_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.znv.protobuf.proto.PmsPersonInfo)
    }
    
    static {
      defaultInstance = new PmsPersonInfo(true);
      com.znv.hk8700.protobuf.PmsEvent.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.znv.protobuf.proto.PmsPersonInfo)
  }
  
  public static final class MsgPmsEvent extends
      com.google.protobuf.GeneratedMessage {
    // Use MsgPmsEvent.newBuilder() to construct.
    private MsgPmsEvent() {
      initFields();
    }
    private MsgPmsEvent(boolean noInit) {}
    
    private static final MsgPmsEvent defaultInstance;
    public static MsgPmsEvent getDefaultInstance() {
      return defaultInstance;
    }
    
    public MsgPmsEvent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.znv.hk8700.protobuf.PmsEvent.internal_static_com_znv_protobuf_proto_MsgPmsEvent_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.znv.hk8700.protobuf.PmsEvent.internal_static_com_znv_protobuf_proto_MsgPmsEvent_fieldAccessorTable;
    }
    
    // optional .com.znv.protobuf.proto.CEmuEvent pms_event = 1;
    public static final int PMS_EVENT_FIELD_NUMBER = 1;
    private boolean hasPmsEvent;
    private com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent pmsEvent_;
    public boolean hasPmsEvent() { return hasPmsEvent; }
    public com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent getPmsEvent() { return pmsEvent_; }
    
    // optional .com.znv.protobuf.proto.CPlaceEvent pgs_event = 2;
    public static final int PGS_EVENT_FIELD_NUMBER = 2;
    private boolean hasPgsEvent;
    private com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent pgsEvent_;
    public boolean hasPgsEvent() { return hasPgsEvent; }
    public com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent getPgsEvent() { return pgsEvent_; }
    
    // optional .com.znv.protobuf.proto.PmsPersonInfo person_info = 33;
    public static final int PERSON_INFO_FIELD_NUMBER = 33;
    private boolean hasPersonInfo;
    private com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo personInfo_;
    public boolean hasPersonInfo() { return hasPersonInfo; }
    public com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo getPersonInfo() { return personInfo_; }
    
    private void initFields() {
      pmsEvent_ = com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.getDefaultInstance();
      pgsEvent_ = com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.getDefaultInstance();
      personInfo_ = com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (hasPmsEvent()) {
        if (!getPmsEvent().isInitialized()) return false;
      }
      if (hasPgsEvent()) {
        if (!getPgsEvent().isInitialized()) return false;
      }
      if (hasPersonInfo()) {
        if (!getPersonInfo().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasPmsEvent()) {
        output.writeMessage(1, getPmsEvent());
      }
      if (hasPgsEvent()) {
        output.writeMessage(2, getPgsEvent());
      }
      if (hasPersonInfo()) {
        output.writeMessage(33, getPersonInfo());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPmsEvent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getPmsEvent());
      }
      if (hasPgsEvent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPgsEvent());
      }
      if (hasPersonInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(33, getPersonInfo());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent result;
      
      // Construct using com.znv.protobuf.proto.PmsEvent.MsgPmsEvent.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent();
        return builder;
      }
      
      protected com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent.getDescriptor();
      }
      
      public com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent getDefaultInstanceForType() {
        return com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent) {
          return mergeFrom((com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent other) {
        if (other == com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent.getDefaultInstance()) return this;
        if (other.hasPmsEvent()) {
          mergePmsEvent(other.getPmsEvent());
        }
        if (other.hasPgsEvent()) {
          mergePgsEvent(other.getPgsEvent());
        }
        if (other.hasPersonInfo()) {
          mergePersonInfo(other.getPersonInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.Builder subBuilder = com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.newBuilder();
              if (hasPmsEvent()) {
                subBuilder.mergeFrom(getPmsEvent());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPmsEvent(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.Builder subBuilder = com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.newBuilder();
              if (hasPgsEvent()) {
                subBuilder.mergeFrom(getPgsEvent());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPgsEvent(subBuilder.buildPartial());
              break;
            }
            case 266: {
              com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.Builder subBuilder = com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.newBuilder();
              if (hasPersonInfo()) {
                subBuilder.mergeFrom(getPersonInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPersonInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.znv.protobuf.proto.CEmuEvent pms_event = 1;
      public boolean hasPmsEvent() {
        return result.hasPmsEvent();
      }
      public com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent getPmsEvent() {
        return result.getPmsEvent();
      }
      public Builder setPmsEvent(com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPmsEvent = true;
        result.pmsEvent_ = value;
        return this;
      }
      public Builder setPmsEvent(com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.Builder builderForValue) {
        result.hasPmsEvent = true;
        result.pmsEvent_ = builderForValue.build();
        return this;
      }
      public Builder mergePmsEvent(com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent value) {
        if (result.hasPmsEvent() &&
            result.pmsEvent_ != com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.getDefaultInstance()) {
          result.pmsEvent_ =
            com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.newBuilder(result.pmsEvent_).mergeFrom(value).buildPartial();
        } else {
          result.pmsEvent_ = value;
        }
        result.hasPmsEvent = true;
        return this;
      }
      public Builder clearPmsEvent() {
        result.hasPmsEvent = false;
        result.pmsEvent_ = com.znv.hk8700.protobuf.EmuServerDevEvent.CEmuEvent.getDefaultInstance();
        return this;
      }
      
      // optional .com.znv.protobuf.proto.CPlaceEvent pgs_event = 2;
      public boolean hasPgsEvent() {
        return result.hasPgsEvent();
      }
      public com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent getPgsEvent() {
        return result.getPgsEvent();
      }
      public Builder setPgsEvent(com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPgsEvent = true;
        result.pgsEvent_ = value;
        return this;
      }
      public Builder setPgsEvent(com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.Builder builderForValue) {
        result.hasPgsEvent = true;
        result.pgsEvent_ = builderForValue.build();
        return this;
      }
      public Builder mergePgsEvent(com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent value) {
        if (result.hasPgsEvent() &&
            result.pgsEvent_ != com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.getDefaultInstance()) {
          result.pgsEvent_ =
            com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.newBuilder(result.pgsEvent_).mergeFrom(value).buildPartial();
        } else {
          result.pgsEvent_ = value;
        }
        result.hasPgsEvent = true;
        return this;
      }
      public Builder clearPgsEvent() {
        result.hasPgsEvent = false;
        result.pgsEvent_ = com.znv.hk8700.protobuf.EmuServerDevEvent.CPlaceEvent.getDefaultInstance();
        return this;
      }
      
      // optional .com.znv.protobuf.proto.PmsPersonInfo person_info = 33;
      public boolean hasPersonInfo() {
        return result.hasPersonInfo();
      }
      public com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo getPersonInfo() {
        return result.getPersonInfo();
      }
      public Builder setPersonInfo(com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPersonInfo = true;
        result.personInfo_ = value;
        return this;
      }
      public Builder setPersonInfo(com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.Builder builderForValue) {
        result.hasPersonInfo = true;
        result.personInfo_ = builderForValue.build();
        return this;
      }
      public Builder mergePersonInfo(com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo value) {
        if (result.hasPersonInfo() &&
            result.personInfo_ != com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.getDefaultInstance()) {
          result.personInfo_ =
            com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.newBuilder(result.personInfo_).mergeFrom(value).buildPartial();
        } else {
          result.personInfo_ = value;
        }
        result.hasPersonInfo = true;
        return this;
      }
      public Builder clearPersonInfo() {
        result.hasPersonInfo = false;
        result.personInfo_ = com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.znv.protobuf.proto.MsgPmsEvent)
    }
    
    static {
      defaultInstance = new MsgPmsEvent(true);
      com.znv.hk8700.protobuf.PmsEvent.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.znv.protobuf.proto.MsgPmsEvent)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_znv_protobuf_proto_PmsPersonInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_znv_protobuf_proto_PmsPersonInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_znv_protobuf_proto_MsgPmsEvent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_znv_protobuf_proto_MsgPmsEvent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017pms_event.proto\022\026com.znv.protobuf.prot" +
      "o\032\027EmuServerDevEvent.proto\"\271\001\n\rPmsPerson" +
      "Info\022\022\n\nperson_idx\030! \002(\t\022\023\n\013person_name\030" +
      "\" \002(\t\022\021\n\tdept_name\030# \002(\t\022\017\n\007id_type\030$ \001(" +
      "\005\022\r\n\005id_no\030% \001(\t\022\r\n\005phone\030& \001(\t\022\016\n\006pinyi" +
      "n\030\' \001(\t\022\014\n\004addr\030( \001(\t\022\022\n\nphoto_path\030) \001(" +
      "\t\022\013\n\003sex\030* \001(\005\"\267\001\n\013MsgPmsEvent\0224\n\tpms_ev" +
      "ent\030\001 \001(\0132!.com.znv.protobuf.proto.CEmuE" +
      "vent\0226\n\tpgs_event\030\002 \001(\0132#.com.znv.protob" +
      "uf.proto.CPlaceEvent\022:\n\013person_info\030! \001(",
      "\0132%.com.znv.protobuf.proto.PmsPersonInfo"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_znv_protobuf_proto_PmsPersonInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_znv_protobuf_proto_PmsPersonInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_znv_protobuf_proto_PmsPersonInfo_descriptor,
              new java.lang.String[] { "PersonIdx", "PersonName", "DeptName", "IdType", "IdNo", "Phone", "Pinyin", "Addr", "PhotoPath", "Sex", },
              com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.class,
              com.znv.hk8700.protobuf.PmsEvent.PmsPersonInfo.Builder.class);
          internal_static_com_znv_protobuf_proto_MsgPmsEvent_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_znv_protobuf_proto_MsgPmsEvent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_znv_protobuf_proto_MsgPmsEvent_descriptor,
              new java.lang.String[] { "PmsEvent", "PgsEvent", "PersonInfo", },
              com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent.class,
              com.znv.hk8700.protobuf.PmsEvent.MsgPmsEvent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.znv.hk8700.protobuf.EmuServerDevEvent.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
